### PR TITLE
atmospherically correct multiple independent images

### PR DESCRIPTION
**Pull request by averms**
This script is similar to ee-atmcorr-timeseries.ipynb but it works on multiple images and can save the correction coefficients for every image (not just the mean). It can also apply those correction coefficients (just uncomment the commented code) and export the images to Earth Engine. It currently relies on absolute imports, which are much cleaner than the previous sys.path hack, so it will only work if you merge #6 too.

### CODE REVIEW

**Comment by samsammurphy** [comment]
Thanks @aaether32323 :pray: 

On the train to London, will take a look at #5 and #6 right now.

**Comment by samsammurphy** [comment]
Looks like you solved an issue that people were brining up in the gee threads, namely exporting corrected images. Nice one!!

I have changed the base of #5 to a new 'dev' branch, as opposed to 'master', and will do the same for #6.

I will merge there then and will work on getting it into master asap.

Cheers!

**Comment by averms** [comment]
Alright thanks!

After testing the code a bit I realized that there is a mistake in the part that writes to a file. It needs to be opened in write mode. I can open a new pull request based on the dev branch.

**Comment by samsammurphy** [comment]
Awesome, go for it!

**Pull request merged**
